language: cpp
compiler:
  - gcc
addons:
  apt:
    packages:
    - cmake
    - libxdamage-dev
    - libx11-dev
    - libxft-dev
    - libxdamage-dev
    - libxext-dev
    - libglib2.0-dev
    - libxml2-dev
    - libcurl4-gnutls-dev
    - liblua5.1-0-dev
    - libtolua++5.1-dev
    - libcairo2-dev
    - gawk
before_script:
  - mkdir build && cd build && cmake ../
script:
  - make -j4
branches:
  only:
    - master
sudo: false
